[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# Показывать короткий вывод с dots + хвост провалившихся тестов
addopts = -v --tb=short

# Минимальный уровень логов в тестах (удобно для отладки)
log_cli = false
log_level = WARNING
asyncio_default_fixture_loop_scope = session