"""auth_tokens

Revision ID: 49ddef25e963
Revises: 3d6c83a0130a
Create Date: 2025-12-18 21:28:48.546481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ddef25e963'
down_revision: Union[str, Sequence[str], None] = '3d6c83a0130a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('curator_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], name=op.f('fk_auth_sessions_curator_id_curators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    op.create_index(op.f('ix_auth_sessions_created_by'), 'auth_sessions', ['created_by'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_updated_by'), 'auth_sessions', ['updated_by'], unique=False)
    op.create_table('oauth_sessions',
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('curator_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], name=op.f('fk_oauth_sessions_curator_id_curators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_sessions')),
    sa.UniqueConstraint('curator_id', 'provider', name='curator_provider_uc')
    )
    op.create_index(op.f('ix_oauth_sessions_created_by'), 'oauth_sessions', ['created_by'], unique=False)
    op.create_index(op.f('ix_oauth_sessions_provider'), 'oauth_sessions', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_sessions_updated_by'), 'oauth_sessions', ['updated_by'], unique=False)
    op.create_unique_constraint('uq_artifact_links_artifact_project', 'artifact_links', ['artifact_id', 'project_id'])
    op.add_column('curators', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.alter_column('curators', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(op.f('uq_curators_email'), 'curators', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_curators_email'), 'curators', type_='unique')
    op.alter_column('curators', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('curators', 'hashed_password')
    op.drop_constraint('uq_artifact_links_artifact_project', 'artifact_links', type_='unique')
    op.drop_index(op.f('ix_oauth_sessions_updated_by'), table_name='oauth_sessions')
    op.drop_index(op.f('ix_oauth_sessions_provider'), table_name='oauth_sessions')
    op.drop_index(op.f('ix_oauth_sessions_created_by'), table_name='oauth_sessions')
    op.drop_table('oauth_sessions')
    op.drop_index(op.f('ix_auth_sessions_updated_by'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_created_by'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
