"""Add all tables

Revision ID: bb313ef92043
Revises: 
Create Date: 2025-11-22 14:35:38.438043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb313ef92043'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('type', sa.Enum('FILE', 'VIDEO', 'LINK', name='artifacttype', native_enum=False), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_created_by'), 'artifacts', ['created_by'], unique=False)
    op.create_index(op.f('ix_artifacts_updated_by'), 'artifacts', ['updated_by'], unique=False)
    op.create_table('curators',
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('outlook_email', sa.String(length=255), nullable=True),
    sa.Column('outlook_access_token', sa.String(length=512), nullable=True),
    sa.Column('outlook_refresh_token', sa.String(length=512), nullable=True),
    sa.Column('outlook_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('google_name', sa.String(length=255), nullable=True),
    sa.Column('google_access_token', sa.String(length=512), nullable=True),
    sa.Column('google_refresh_token', sa.String(length=512), nullable=True),
    sa.Column('google_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tg_link', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curators')),
    sa.UniqueConstraint('google_id', name=op.f('uq_curators_google_id')),
    sa.UniqueConstraint('outlook_email', name=op.f('uq_curators_outlook_email'))
    )
    op.create_index(op.f('ix_curators_created_by'), 'curators', ['created_by'], unique=False)
    op.create_index(op.f('ix_curators_expires_at'), 'curators', ['expires_at'], unique=False)
    op.create_index(op.f('ix_curators_is_revoked'), 'curators', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_curators_refresh_token'), 'curators', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_curators_updated_by'), 'curators', ['updated_by'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('goal', sa.String(length=1000), nullable=True),
    sa.Column('requirements', sa.String(length=2000), nullable=True),
    sa.Column('eval_criteria', sa.String(length=1000), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Enum('AUTUMN', 'SPRING', name='semester', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='projectstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_projects_updated_by'), 'projects', ['updated_by'], unique=False)
    op.create_table('students',
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tg_link', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_index(op.f('ix_students_created_by'), 'students', ['created_by'], unique=False)
    op.create_index(op.f('ix_students_updated_by'), 'students', ['updated_by'], unique=False)
    op.create_table('tasks',
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_updated_by'), 'tasks', ['updated_by'], unique=False)
    op.create_table('evaluations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('curator_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('LIKE', 'DISLIKE', name='evaluationtype', native_enum=False), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], name=op.f('fk_evaluations_curator_id_curators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_evaluations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'curator_id', 'type', 'id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('project_id', 'curator_id', 'type', name='uq_evaluations_project_curator_type')
    )
    op.create_index(op.f('ix_evaluations_created_by'), 'evaluations', ['created_by'], unique=False)
    op.create_index(op.f('ix_evaluations_updated_by'), 'evaluations', ['updated_by'], unique=False)
    op.create_table('milestones',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('CONTROL_POINT', 'PROTECTION', name='milestonetype', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_milestones_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    op.create_index(op.f('ix_milestones_created_by'), 'milestones', ['created_by'], unique=False)
    op.create_index(op.f('ix_milestones_updated_by'), 'milestones', ['updated_by'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_link', sa.String(length=512), nullable=True),
    sa.Column('curator_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], name=op.f('fk_teams_curator_id_curators'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_created_by'), 'teams', ['created_by'], unique=False)
    op.create_index(op.f('ix_teams_updated_by'), 'teams', ['updated_by'], unique=False)
    op.create_table('curator_teams',
    sa.Column('curator_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], name=op.f('fk_curator_teams_curator_id_curators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_curator_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curator_id', 'team_id', name=op.f('pk_curator_teams')),
    sa.UniqueConstraint('curator_id', 'team_id', name='uq_curator_teams_curator_team')
    )
    op.create_table('meetings',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resume', sa.String(length=2000), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='meetingstatus', native_enum=False), nullable=False),
    sa.Column('previous_meeting_id', sa.UUID(), nullable=True),
    sa.Column('next_meeting_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['next_meeting_id'], ['meetings.id'], name=op.f('fk_meetings_next_meeting_id_meetings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_meeting_id'], ['meetings.id'], name=op.f('fk_meetings_previous_meeting_id_meetings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_meetings_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings'))
    )
    op.create_index(op.f('ix_meetings_created_by'), 'meetings', ['created_by'], unique=False)
    op.create_index(op.f('ix_meetings_updated_by'), 'meetings', ['updated_by'], unique=False)
    op.create_table('project_teams',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_teams_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_project_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'team_id', name=op.f('pk_project_teams')),
    sa.UniqueConstraint('project_id', 'team_id', name='uq_project_teams_project_team')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('study_group', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_team_members_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'student_id', 'id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('team_id', 'student_id', name='uq_team_members_team_student')
    )
    op.create_index(op.f('ix_team_members_created_by'), 'team_members', ['created_by'], unique=False)
    op.create_index(op.f('ix_team_members_updated_by'), 'team_members', ['updated_by'], unique=False)
    op.create_table('artifact_links',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('(project_id IS NOT NULL AND meeting_id IS NULL) OR (project_id IS NULL AND meeting_id IS NOT NULL)', name=op.f('ck_artifact_links_ck_artifact_links_one_fk')),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_artifact_links_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_artifact_links_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_artifact_links_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_links')),
    sa.UniqueConstraint('artifact_id', 'meeting_id', name='uq_artifact_links_artifact_meeting'),
    sa.UniqueConstraint('artifact_id', 'project_id', name='uq_artifact_links_artifact_project')
    )
    op.create_index(op.f('ix_artifact_links_artifact_id'), 'artifact_links', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_links_created_by'), 'artifact_links', ['created_by'], unique=False)
    op.create_index(op.f('ix_artifact_links_meeting_id'), 'artifact_links', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_artifact_links_project_id'), 'artifact_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_artifact_links_updated_by'), 'artifact_links', ['updated_by'], unique=False)
    op.create_table('attendances',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('curator_id', sa.UUID(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('(student_id IS NOT NULL AND curator_id IS NULL) OR (student_id IS NULL AND curator_id IS NOT NULL)', name=op.f('ck_attendances_ck_attendances_one_fk')),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], name=op.f('fk_attendances_curator_id_curators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_attendances_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_attendances_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendances')),
    sa.UniqueConstraint('meeting_id', 'curator_id', name='uq_attendances_meeting_curator'),
    sa.UniqueConstraint('meeting_id', 'student_id', name='uq_attendances_meeting_student')
    )
    op.create_index(op.f('ix_attendances_created_by'), 'attendances', ['created_by'], unique=False)
    op.create_index(op.f('ix_attendances_curator_id'), 'attendances', ['curator_id'], unique=False)
    op.create_index(op.f('ix_attendances_meeting_id'), 'attendances', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_attendances_student_id'), 'attendances', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendances_updated_by'), 'attendances', ['updated_by'], unique=False)
    op.create_table('meeting_tasks',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_tasks_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_meeting_tasks_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'task_id', name=op.f('pk_meeting_tasks')),
    sa.UniqueConstraint('meeting_id', 'task_id', name='uq_meeting_tasks_meeting_task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_tasks')
    op.drop_index(op.f('ix_attendances_updated_by'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_student_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_meeting_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_curator_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_created_by'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_artifact_links_updated_by'), table_name='artifact_links')
    op.drop_index(op.f('ix_artifact_links_project_id'), table_name='artifact_links')
    op.drop_index(op.f('ix_artifact_links_meeting_id'), table_name='artifact_links')
    op.drop_index(op.f('ix_artifact_links_created_by'), table_name='artifact_links')
    op.drop_index(op.f('ix_artifact_links_artifact_id'), table_name='artifact_links')
    op.drop_table('artifact_links')
    op.drop_index(op.f('ix_team_members_updated_by'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_created_by'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('project_teams')
    op.drop_index(op.f('ix_meetings_updated_by'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_by'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_table('curator_teams')
    op.drop_index(op.f('ix_teams_updated_by'), table_name='teams')
    op.drop_index(op.f('ix_teams_created_by'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_milestones_updated_by'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_created_by'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_evaluations_updated_by'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_created_by'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_tasks_updated_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_students_updated_by'), table_name='students')
    op.drop_index(op.f('ix_students_created_by'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_projects_updated_by'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_curators_updated_by'), table_name='curators')
    op.drop_index(op.f('ix_curators_refresh_token'), table_name='curators')
    op.drop_index(op.f('ix_curators_is_revoked'), table_name='curators')
    op.drop_index(op.f('ix_curators_expires_at'), table_name='curators')
    op.drop_index(op.f('ix_curators_created_by'), table_name='curators')
    op.drop_table('curators')
    op.drop_index(op.f('ix_artifacts_updated_by'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_created_by'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
