"""project applications infrastructure

Revision ID: 5608ea3317f6
Revises: 9a3489bce8a6
Create Date: 2026-05-25 18:26:03.426937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5608ea3317f6"
down_revision: Union[str, Sequence[str], None] = "9a3489bce8a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_applications",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("team_name", sa.String(length=255), nullable=False),
        sa.Column("vk_sender_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SEEN",
                "UNSEEN",
                "ACCEPTED",
                "DECLINED",
                name="projectapplicationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("mean_project_score", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_applications_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_applications")),
    )
    op.create_index(
        op.f("ix_project_applications_created_by"),
        "project_applications",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_applications_updated_by"),
        "project_applications",
        ["updated_by"],
        unique=False,
    )
    op.create_table(
        "project_application_members",
        sa.Column("project_application_id", sa.UUID(), nullable=False),
        sa.Column("fullname", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.Column("study_group", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_application_id"],
            ["project_applications.id"],
            name=op.f(
                "fk_project_application_members_project_application_id_project_applications"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_application_members")),
    )
    op.create_index(
        op.f("ix_project_application_members_created_by"),
        "project_application_members",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_application_members_updated_by"),
        "project_application_members",
        ["updated_by"],
        unique=False,
    )
    op.create_table(
        "project_interviews",
        sa.Column("project_application_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("curators_rate", sa.Integer(), nullable=True),
        sa.Column(
            "interview_status",
            sa.Enum(
                "RATING",
                "PENDING",
                "ACCEPTED",
                "DECLINED",
                name="projectinterviewstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("resume", sa.String(length=2000), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELED",
                name="meetingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_application_id"],
            ["project_applications.id"],
            name=op.f(
                "fk_project_interviews_project_application_id_project_applications"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_interviews")),
    )
    op.create_index(
        op.f("ix_project_interviews_created_by"),
        "project_interviews",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_interviews_updated_by"),
        "project_interviews",
        ["updated_by"],
        unique=False,
    )
    op.add_column("project_teams", sa.Column("final_score", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_teams", "final_score")
    op.drop_index(
        op.f("ix_project_interviews_updated_by"), table_name="project_interviews"
    )
    op.drop_index(
        op.f("ix_project_interviews_created_by"), table_name="project_interviews"
    )
    op.drop_table("project_interviews")
    op.drop_index(
        op.f("ix_project_application_members_updated_by"),
        table_name="project_application_members",
    )
    op.drop_index(
        op.f("ix_project_application_members_created_by"),
        table_name="project_application_members",
    )
    op.drop_table("project_application_members")
    op.drop_index(
        op.f("ix_project_applications_updated_by"), table_name="project_applications"
    )
    op.drop_index(
        op.f("ix_project_applications_created_by"), table_name="project_applications"
    )
    op.drop_table("project_applications")
    # ### end Alembic commands ###
