"""project application model

Revision ID: b12db1f3c536
Revises: 74459f8b88a7
Create Date: 2026-05-06 21:18:24.406003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12db1f3c536'
down_revision: Union[str, Sequence[str], None] = '74459f8b88a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_applications',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('vk_sender_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'DECLINED', 'ACCEPTED', 'INTERVIEW', name='projectapplicationstatus', native_enum=False), nullable=False),
    sa.Column('mean_project_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_project_applications_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_applications_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_project_applications_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_applications')),
    sa.UniqueConstraint('project_id', 'team_id', name='uq_project_applications_team')
    )
    op.create_index(op.f('ix_project_applications_created_by'), 'project_applications', ['created_by'], unique=False)
    op.create_index(op.f('ix_project_applications_updated_by'), 'project_applications', ['updated_by'], unique=False)
    op.add_column('project_teams', sa.Column('final_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_teams', 'final_score')
    op.drop_index(op.f('ix_project_applications_updated_by'), table_name='project_applications')
    op.drop_index(op.f('ix_project_applications_created_by'), table_name='project_applications')
    op.drop_table('project_applications')
    # ### end Alembic commands ###
