"""increase string field restrictions

Revision ID: a0ebdb94bfc1
Revises: 3a990e3fa387
Create Date: 2026-06-17 17:57:59.158198

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0ebdb94bfc1"
down_revision: Union[str, Sequence[str], None] = "3a990e3fa387"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "artifacts",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "artifacts",
        "description",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=5000),
        existing_nullable=True,
    )
    op.alter_column(
        "meetings",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "meetings",
        "resume",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=5000),
        existing_nullable=True,
    )
    op.alter_column(
        "milestones",
        "title",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "milestones",
        "description",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=5000),
        existing_nullable=True,
    )
    op.alter_column(
        "project_applications",
        "description",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=5000),
        existing_nullable=True,
    )
    op.alter_column(
        "project_applications",
        "team_name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "project_interviews",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "project_interviews",
        "resume",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=5000),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "projects",
        "description",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=5000),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "goal",
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.String(length=5000),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "requirements",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=5000),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "eval_criteria",
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.String(length=5000),
        existing_nullable=True,
    )
    op.alter_column(
        "tasks",
        "description",
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.String(length=5000),
        existing_nullable=False,
    )
    op.alter_column(
        "teams",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teams",
        "name",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "description",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "projects",
        "eval_criteria",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=1000),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "requirements",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "goal",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=1000),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "description",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "name",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "project_interviews",
        "resume",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "project_interviews",
        "name",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "project_applications",
        "team_name",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "project_applications",
        "description",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "milestones",
        "description",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "milestones",
        "title",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "meetings",
        "resume",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "meetings",
        "name",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "artifacts",
        "description",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts",
        "name",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
