"""empty message

Revision ID: 74459f8b88a7
Revises: 49ddef25e963
Create Date: 2026-01-04 10:59:13.863455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74459f8b88a7'
down_revision: Union[str, Sequence[str], None] = '49ddef25e963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curators', sa.Column('avatar_s3_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curators', 'avatar_s3_path')
    # ### end Alembic commands ###
