{{- if .Values.pgadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-pgadmin
spec:
  type: {{ .Values.pgadmin.service.type }}
  selector:
    app: pgadmin
  ports:
    - port: {{ .Values.pgadmin.service.port }}
      targetPort: 8080
{{- end }}
