apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
type: Opaque
stringData:
{{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
