from app.domain.entities.base_entity import BaseEntity
from app.domain.entities.artifacts.artifact import Artifact
from app.domain.entities.artifacts.artifact_link import ArtifactLink
from app.domain.entities.meetings.attendance import Attendance
from app.domain.entities.base_entity import BaseEntity
from app.domain.entities.persons.person import Person
from app.domain.entities.meetings.meetings import Meeting
from app.domain.entities.project_entities.project import Project
from app.domain.entities.persons.student import Student
from app.domain.entities.meetings.task import Task
from app.domain.entities.team.team import Team
from app.domain.entities.team.team_member import TeamMember
from app.domain.entities.persons.curator import Curator