from app.domain.entities.base_entity import BaseEntity
from app.domain.entities.project_entities.artifacts.artifact import Artifact
from app.domain.entities.project_entities.artifacts.artifact_link import ArtifactLink
from app.domain.entities.project_entities.meetings.attendance import Attendance
from app.domain.entities.base_entity import BaseEntity
from app.domain.entities.human_entities.human_entity import Human
from app.domain.entities.project_entities.meetings.meetings import Meeting
from app.domain.entities.project_entities.project import Project
from app.domain.entities.human_entities.student import Student
from app.domain.entities.project_entities.task import Task
from app.domain.entities.project_entities.team import Team
from app.domain.entities.human_entities.team_member import TeamMember
from app.domain.entities.human_entities.user_curator import User